title: Nerd In. Switzerland
description: >
  Just blogging about things that I, in most cases this is something
  nerdy and or technology related.
author:
  fullname: Erik Jan de Wit
  googleplus: https://plus.google.com/+ErikJandeWit
  github: edewit
  mastodon: social.linux.pizza/@edewit
  disqus: nerdinch
highlightstyle: ''
