quarkus.qute.alt-expr-syntax=true
quarkus.qute.strict-rendering=false
quarkus.qute.property-not-found-strategy=NOOP

site.url=https://blog.nerdin.ch
site.date-format=yyyy-MM-dd['T'HH:mm:ss[.SSS]][XXX]
site.escaped-pages=posts/**
site.slugify-files=false

site.collections.posts.layout=post
site.collections.posts.link=/:year/:month/:day/:name/

quarkus.roq.data.dir=_data
quarkus.web-bundler.bundling.external=/assets/*
